### ISSUE TITLE
Unable to union with polygons of unequal number of points

### ISSUE THREAD

**Issue by theredcomputer** [Turfjs/turf-union#12]
Hello,

I have two polygons I'm attempting to merge. However, these polygons do not have an equal amount of boundary points, and the union function continually returns an empty dictionary. Are polygons required to have the same number of points to use the union function? If so, is there a way to make this work?

**Comment by theredcomputer** [comment]
Figured this issue out. I assumed the poly.geometry.coordinates value took a double array when it requires a triple array. Marking as resolved.

**Comment by DenisCarriere** [comment]
@theredcomputer Thanks for opening up this issue, however could you post your question to the main Turf repo since `turf-union` has been merged as `@turf/union`.

https://github.com/Turfjs/turf

👍 Just noticed you closed it
